os:
  - linux
  - osx

sudo: false

language: python
python:
  - 3.4

install:
  - travis_retry pip3 install -q .

script:
  - grab-site --help
  - gs-dump-urls --help
  - grab-site --1 https://github.com/ludios/grab-site
