sudo: false

language: python
python:
  - 3.4

install:
  - travis_retry pip3 install .

script:
  - grab-site --help
  - grab-site --1 https://www.google.com/
  - gs-dump-urls --help
  - ls -l www.google.com*
  - gs-dump-urls www.google.com*/wpull.db done
  - python3 -c 'import libgrabsite.server'
