sudo: false

language: python
python:
  - 3.4

install:
  - travis_retry pip3 install .

script:
  - grab-site --help
  - grab-site --1 https://github.com/ludios/grab-site
  - gs-dump-urls --help
  - ls -l github.com*
  - gs-dump-urls github.com*/wpull.db done
  - python3 -c 'import libgrabsite.server'
